site_name: JMV España — Documentación
site_url: https://jmv-espana.github.io/documentacion-publica
repo_url: https://github.com/JMV-Espana/documentacion-publica
repo_name: documentacion-publica

theme:
  name: material
  language: es
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.action.edit   # añade un lápiz "Editar esta página" que lleva directo al editor de GitHub

plugins:
  - search
  - awesome-nav

nav:
  - Inicio: index.md
  - Corporativo: 
    - Estatutos: estatutos.md
    - Estilo de vida: estilo-de-vida.md
    - Políticas: [...]
  - Secretaría: [...]
  - Tesorería: [...]
  - Actividades: [...]
  - Google Workspace: [...]
  - Identidad visual: [...]
  - Plantillas: [...]
  - Contacto: contacto.md